//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int id { get; set; }
        public string webname { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string copyright { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}
